spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kusaba
    username: root
    password: root
  thymeleaf:
    mode: HTML5
  mvc:
    locale: en_US

server:
  port: 12345
  error.whitelabel.enabled: false
  
multipart:
  maxFileSize: 10Mb
  
chanzinho:
  maxpages: 10
  indexreplies: 3
  op.requirefile: true